### ISSUE TITLE
Needs an option to crawl before and after login

### ISSUE THREAD

**Issue by GriffinSauce** [oyvindeh/ucss#39]
Right now providing headers or a login function means login is immediately done. This means pages that respond to a user being logged in/out are not processed properly.

Easiest solution would be to provide an option that forces a scan before and after setting the headers and auth.

**Comment by oyvindeh** [comment]
Thanks for reporting this issue, and sorry for the slow response.

Looked into this now, and I'm not sure I understand the problem. I tried to set up a more fine-grained test case than what was present, to see if different selectors can be detected when logged in than when logged out (and vice versa). It seems to work like expected.

From re-reading the code (it's been a while since I wrote it), it does indeed log in before it does anything else, to get the cookie. [It will then visit each page twice, both with a cookie header set, and without](https://github.com/oyvindeh/ucss/blob/7d20e49fbf948060e8e5d8aed845806405b96ae0/lib/html.js#L131-140), thus it should visit each URL both as a logged in user and a logged out user.

What back-end framework are you targeting? Is it possible that it keeps you logging in, even if you don't send a cookie?

Please let me know if I've missed something here.

**Comment by GriffinSauce** [comment]
It's might be due to my setup. I'm targeting an Express with Passport, will do some digging. Thanks for the response.

**Comment by oyvindeh** [comment]
Closing this; please reopen if there is still a problem.
